### ISSUE TITLE
external component cannot be included directly in esphome

### ISSUE THREAD

**Issue by andreas-bulling** [persuader72/esphome-components#12]
I tried to include the component directly - like other components:

```
external_components:
  - source: github://persuader72/esphome-components@master
    refresh: 0s
    components: [shelly_dallas]
```

This doesn't work, error message:
```
Could not find components folder for source. Please check the source contains a 'components' or 'esphome/components' folder.
    source: github://persuader72/esphome-components@master
    refresh: 0s
    components: 
      - shelly_dallas
```
