### ISSUE TITLE
Shelly Plus add-on not compiling

### ISSUE THREAD

**Issue by pojlFDlxCOvZ4Kg8y1l4** [persuader72/esphome-components#15]
Hello,

After some fiddling I can't seem to get the add-on with the dallas component to compile.
It spits out weird errors, both `master` and `dev` trains.  
I've tried to add `#include <vector>` into the mentioned files, which made the offending lines go away.  But ESPHome keeps bugging about "error: expected initializer before 'ESPOneWire'".
ESPHome's default `dallas` does compile but finds no sensors, also leaving out the `shelly_dallas` custom compents compiles.
I do not know how to fix this myself, can you help me?  

Hardware: Shelly 1PM Plus with the Shelly Plus Add-on, and two DS18b20 sensors.
[GPIO pins are different on the plus add-on](https://github.com/esphome/feature-requests/issues/2034#issuecomment-1529131339), `pin: 1`, `pin_a: 0`

YAML ([basic config from ESPHome devices](https://devices.esphome.io/devices/Shelly-Plus-1PM)):
```
substitutions:
  device_name: "Thermostat HVAC"
  # Higher value gives lower watt readout
  current_res: "0.001"
  # Lower value gives lower voltage readout
  voltage_div: "1925"

esphome:
  name: thermostat-livingroom
  platformio_options:
    board_build.f_cpu: 160000000L

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: debug

api:
  encryption:
    key: !secret api

ota:
  password: !secret ota

web_server:
    port: 80

shelly_dallas:
    pin_a: GPIO1
    pin_b: GPIO0

time:
  - platform: homeassistant

output:
  - platform: gpio
    id: "relay_output"
    pin: GPIO26

switch:
  - platform: output
    id: "relay"
    name: "${device_name} Relay"
    output: "relay_output"

binary_sensor:
  - platform: gpio
    name: "${device_name} Switch"
    pin: GPIO4
    on_press:
      then:
        - switch.turn_on: "relay"
    on_release:
      then:
        - switch.turn_off: "relay"
    filters:
      - delayed_on_off: 50ms

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: "${device_name} Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: "80.0"
        then:
          - switch.turn_off: "relay"
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: adc
    id: temp_analog_reading
    pin: GPIO32
    attenuation: 11db

  - platform: adc
    name: "${device_name} Relay Supply Voltage"
    pin: GPIO33
    attenuation: 11db
    filters:
      - multiply: 8

  - platform: hlw8012
    model: BL0937
    sel_pin:
      number: GPIO23
      inverted: true
    cf_pin: GPIO5
    cf1_pin: GPIO18
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: "${device_name} Current"
      unit_of_measurement: A
      accuracy_decimals: 3
      icon: mdi:flash-outline
    voltage:
      name: "${device_name} Voltage"
      unit_of_measurement: V
      accuracy_decimals: 1
      icon: mdi:flash-outline
    power:
      name: "${device_name} Power"
      unit_of_measurement: W
      id: power
      icon: mdi:flash-outline
      on_value_range:
        - above: "3600"
          then:
            - switch.turn_off: "relay"
    change_mode_every: 2
    update_interval: 10s
  - platform: total_daily_energy
    name: "${device_name} Daily energy consumed"
    power_id: power
    filters:
        - multiply: 0.001
    unit_of_measurement: kWh
    icon: mdi:clock-alert
```

Compile log:
``` 
INFO ESPHome 2023.8.3
INFO Reading configuration /config/esphome/thermostat-livingroom.yaml...
WARNING GPIO0 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Detected timezone 'Europe/Amsterdam'
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing thermostat-livingroom (board: esp32doit-devkit-v1; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 160MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40405.230623 (4.4.5) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Dependency Graph
|-- noise-c @ 0.1.4
|-- ArduinoJson @ 6.18.5
Compiling /data/thermostat-livingroom/.pioenvs/thermostat-livingroom/src/esphome/components/shelly_dallas/shelly_dallas_component.o
Compiling /data/thermostat-livingroom/.pioenvs/thermostat-livingroom/src/esphome/components/shelly_dallas/shelly_esp_one_wire.o
In file included from src/esphome/components/shelly_dallas/shelly_esp_one_wire.cpp:1:
src/esphome/components/shelly_dallas/shelly_esp_one_wire.h:55:8: error: 'vector' in namespace 'std' does not name a template type
   std::vector<uint64_t> search_vec();
        ^~~~~~
src/esphome/components/shelly_dallas/shelly_esp_one_wire.h:55:3: note: 'std::vector' is defined in header '<vector>'; did you forget to '#include <vector>'?
src/esphome/components/shelly_dallas/shelly_esp_one_wire.h:5:1:
+#include <vector>
 
src/esphome/components/shelly_dallas/shelly_esp_one_wire.h:55:3:
   std::vector<uint64_t> search_vec();
   ^~~
src/esphome/components/shelly_dallas/shelly_esp_one_wire.cpp:19:26: error: expected initializer before 'ESPOneWire'
 bool HOT ICACHE_RAM_ATTR ESPOneWire::reset() {
                          ^~~~~~~~~~
src/esphome/components/shelly_dallas/shelly_esp_one_wire.cpp:45:26: error: expected initializer before 'ESPOneWire'
 void HOT ICACHE_RAM_ATTR ESPOneWire::write_bit(bool bit) {
                          ^~~~~~~~~~
src/esphome/components/shelly_dallas/shelly_esp_one_wire.cpp:66:26: error: expected initializer before 'ESPOneWire'
 bool HOT ICACHE_RAM_ATTR ESPOneWire::read_bit() {
                          ^~~~~~~~~~
src/esphome/components/shelly_dallas/shelly_esp_one_wire.cpp:83:22: error: expected initializer before 'ESPOneWire'
 void ICACHE_RAM_ATTR ESPOneWire::write8(uint8_t val) {
                      ^~~~~~~~~~
src/esphome/components/shelly_dallas/shelly_esp_one_wire.cpp:89:22: error: expected initializer before 'ESPOneWire'
 void ICACHE_RAM_ATTR ESPOneWire::write64(uint64_t val) {
                      ^~~~~~~~~~
src/esphome/components/shelly_dallas/shelly_esp_one_wire.cpp:95:25: error: expected initializer before 'ESPOneWire'
 uint8_t ICACHE_RAM_ATTR ESPOneWire::read8() {
                         ^~~~~~~~~~
src/esphome/components/shelly_dallas/shelly_esp_one_wire.cpp:102:26: error: expected initializer before 'ESPOneWire'
 uint64_t ICACHE_RAM_ATTR ESPOneWire::read64() {
                          ^~~~~~~~~~
src/esphome/components/shelly_dallas/shelly_esp_one_wire.cpp:109:22: error: expected initializer before 'ESPOneWire'
 void ICACHE_RAM_ATTR ESPOneWire::select(uint64_t address) {
                      ^~~~~~~~~~
src/esphome/components/shelly_dallas/shelly_esp_one_wire.cpp:113:22: error: expected initializer before 'ESPOneWire'
 void ICACHE_RAM_ATTR ESPOneWire::reset_search() {
                      ^~~~~~~~~~
src/esphome/components/shelly_dallas/shelly_esp_one_wire.cpp:119:30: error: expected initializer before 'ESPOneWire'
 uint64_t HOT ICACHE_RAM_ATTR ESPOneWire::search() {
                              ^~~~~~~~~~
src/esphome/components/shelly_dallas/shelly_esp_one_wire.cpp:204:39: error: expected initializer before 'ESPOneWire'
 std::vector<uint64_t> ICACHE_RAM_ATTR ESPOneWire::search_vec() {
                                       ^~~~~~~~~~
src/esphome/components/shelly_dallas/shelly_esp_one_wire.cpp:214:22: error: expected initializer before 'ESPOneWire'
 void ICACHE_RAM_ATTR ESPOneWire::skip() {
                      ^~~~~~~~~~
src/esphome/components/shelly_dallas/shelly_esp_one_wire.cpp:221:25: error: expected initializer before '*' token
 uint8_t ICACHE_RAM_ATTR *ESPOneWire::rom_number8_() { return reinterpret_cast<uint8_t *>(&this->rom_number_); }
                         ^
*** [/data/thermostat-livingroom/.pioenvs/thermostat-livingroom/src/esphome/components/shelly_dallas/shelly_esp_one_wire.o] Error 1
========================== [FAILED] Took 5.59 seconds ==========================
```
