### ISSUE TITLE
Found no sensors

### ISSUE THREAD

**Issue by MarkoPaasila** [persuader72/esphome-components#6]
What could be the reason? 
```
[12:59:01][C][dallas.sensor:072]: ShellyDallasComponent:
[12:59:01][C][dallas.sensor:073]:   In Pin: GPIO3
[12:59:01][C][dallas.sensor:074]:   Out Pin: GPIO0
[12:59:01][C][dallas.sensor:075]:   Update Interval: 60.0s
[12:59:01][W][dallas.sensor:078]:   Found no sensors!
```
I'm using dev branch. Here's the relevant part from my config:
```
shelly_dallas:
  pin_a: GPIO3
  pin_b: GPIO0
    
sensor:
#  - platform: shelly_dallas
#    address: 0xCA011938282E5128
#    index: 0
#    name: "Living Room Floor"
#    accuracy_decimals: 1
#    unit_of_measurement: "°C"
#    device_class: temperature
#    state_class: measurement
#    icon: "mdi:thermometer"
```
The sensor is commented out. I've tried the sensor component using the address (which is wrong as I can't get the correct one) and the index parameter (according to [ESPHome Dallas page](https://esphome.io/components/sensor/dallas.html?highlight=dallas#id1). Neither work. I'm pretty sure the sensor + shelly-addon-board work, since I've used them with the stock firmware.
